<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="sd.css">
    <title>Document</title>
</head>
<body>
    <form action="form.php" method="POST">

    <label>Nome</label>
    <input type="text" name="nome"  style=" background-color:black;  color:azure;">
    <label>Idade</label>
    <input type="number" name="idade" style=" background-color:black;  color:azure;">
    <button type="submit" >enviar</button>
    </form>
</body>
</html>